on:
  pull_request:
    branches:
      - main

jobs:
  test-comment:
    permissions:
      pull-requests: 'write'
      discussions: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/comment-on-pr
        with:
          pr_url: "https://gilzow.com/"