name: Repo playing
on:
  workflow_dispatch:

jobs:
  adjust-repo:
    runs-on: ubuntu-latest
    name: check out and an examine the repo
    steps:
      - uses: actions/checkout@v4
        id: checkout-repo
        with:
          fetch-depth: 0
      - id: tests-remotes
        run: |
          git remote -v
      - id: show-branches
        run: |
          branches=$(git branch -a)
          echo $branches;
      - id: checkout-update
        run: |
          git fetch --all
          update=$(git ls-remote --heads origin update)
          if [ -z "${update}" ]; then
            echo "update isn't a remote branch"
            echo "check it out or create it"
            git switch update 2>/dev/null || git switch -c update
          else
            echo "update is a remote branch"
            echo "check out the remote branch"
            git switch --track origin/update
          fi
          
          # make sure we're up-to-date with our own main
          # git pull origin main
          # add the remote 
          # git remote add upstream git@git.blah.blah
          # pull from the remote
          # git pull upstream main
          
