# This is called after the deployed environment is ready to be checked
name: Regularly scheduled check links
on:
  schedule:
    - cron: "0 2 * * 1,4"
  workflow_dispatch:
    inputs:
      url:
        description: 'Site to check for broken links'
        required: true
        type: string
        default: 'https://docs.platform.sh/'

jobs:
  check-links:
    name: Check links
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: install linkchecker
        id: install-linkchecker
        run: |
          pip3 install linkchecker

      - name: checkout xml to markdown
        uses: actions/checkout@v4
        with:
          repository: platformsh/linkchecker-xml2md

      - name: checkout linkchecker config
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            ./.github/workflows/linkchecker/linkcheckerrc
          sparse-checkout-cone-mode: false
          path: linkchecker
      - name: install-parser
        run: |
          pip3 install -r requirements.txt

      - name: Set URL to scan
        id: set-url
        shell: bash
        run: |
          # If this is a workflow dispatch, then use what was entered.
          # If not, then use the repository variable SCAN_URL if it is set
          # if not, fall back to the hard-coded default
          scanURL="https://docs.platform.sh/"
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            scanURL="${{ inputs.url }}"
          elif [[ -n "${{ vars.SCAN_URL }}" ]]; then
            scanURL="${{ vars.SCAN_URL }}"
          fi

          echo "scanURL=${scanURL}" >> "$GITHUB_ENV"

      - name: Run linkchecker
        id: run-link-checker
        continue-on-error: true
        shell: bash
        run: |
          echo "::notice::Scanning ${{ inputs.url }} for broken links."
          echo "before we start, let's see if we have our stuff..."
          tree ./linkchecker
          # if linkchecker exits with a non-zero then it means broken links were found.
          scan=$(linkchecker ${{ env.scanURL }} -f ./linkchecker/.github/workflows/linkchecker/linkcheckerrc -F xml/utf_8/brokenlinks.xml )
          result=$?
          if [[ $result -ne 0 ]]; then
            echo "::notice::Broken links detected."
          fi


      - name: Convert xml to markdown
        if: ${{ steps.run-link-checker.outcome == 'failure' }}
        run: |
          ./xml2md.py brokenlinks.xml > broken_links.md

      - name: Report no broken links
        if: ${{ steps.run-link-checker.outcome == 'success' }}
        run: |
          echo "::notice::No broken links were detected"

      - name: check message size
        id: check-msg-size
        if: ${{ steps.run-link-checker.outcome == 'failure' }}
        run: |
          artifact="false"
          sizeOfMessage=$(cat broken_links.md | wc -c)
          echo "::notice::Size of report: ${sizeOfMessage}"
          # the size of a comment in an issue is 65536
          if [ "${sizeOfMessage}" -gt 65000 ]; then
            # we'll need to store the broken_links.md file as an aritifact
            artifact="true"
          fi

          echo "artifact=${artifact}" >> $GITHUB_ENV

      - name: where is everything
        id: where-is-everything
        run: |
          echo "::notice::We are at ${PWD}"
          echo "::notice::Action path is ${{ github.action_path }}"
          ls -al

      - name: Upload artifact if applicable
        id: upload-artifact
        if: ${{ steps.run-link-checker.outcome == 'failure' && env.artifact == 'true' }}
        uses: actions/upload-artifact@v4
        with:
          name: broken-links
          path: |
            ./broken_links.md

      - name: Create issue
        id: create-issue
        if: ${{ steps.run-link-checker.outcome == 'failure' }}
        env:
          ARTIFACT: ${{ env.artifact }}
        uses: actions/github-script@v6
        with:
          script: |
            const { ARTIFACT } = process.env
            var fs = require('fs');
            //
            failMsg = ':bug: Broken links detected'

            if ('true' == ARTIFACT) {
              address = `https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}#artifacts`
              var bodyMsg = `Broken links found. Please view the report artifact at ${address}`
            } else {
              var bodyMsg = fs.readFileSync('broken_links.md','utf8');
            }

            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: failMsg,
              body: bodyMsg,
              labels: ['broken-links'],
            })
      - name: Setup tmate session
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3